[features]
seeds = false
[programs.localnet]
solana_trading_app = "Aj8Lne9J5iotJxRMJuL3ATowQwqwh9ZqAWr44wJkRSRY"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/Users/peteryang/.config/solana/id.json"

[scripts]
test = "mocha -p ./tsconfig.json -t 1000000 tests/*"
